# Generated by Django 5.0.2 on 2024-03-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('policy_description', models.TextField(max_length=2000)),
                ('car_model', models.CharField(max_length=100)),
                ('production_year', models.PositiveIntegerField(default=2024)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Electric', 'Electric'), ('Hydrogen', 'Hydrogen'), ('Biodiesel', 'Biodiesel')], max_length=100)),
                ('mileage', models.PositiveIntegerField()),
                ('average_year_mileage', models.PositiveSmallIntegerField(choices=[(1, 'Poniżej 5 tys. km'), (2, 'do 10 tys. km'), (3, 'do 20 tys. km'), (4, 'powyżej 20 tys. km')])),
                ('is_rented', models.BooleanField(default=False)),
                ('number_of_owners', models.PositiveSmallIntegerField()),
                ('driver_under_26', models.BooleanField(default=False)),
            ],
        ),
    ]
