# Generated by Django 5.0.2 on 2024-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinsurance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='valid_to',
            field=models.DateField(auto_now=True),
        ),
    ]
