# Generated by Django 5.0.2 on 2024-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_houseinsurance_remove_carinsurance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinsurance',
            name='policy_type',
            field=models.CharField(choices=[('Standard OC', 'Standard OC'), ('OC + AC', 'OC + AC'), ('PREMIUM', 'PREMIUM')], default='Standard OC', max_length=100),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='average_year_mileage',
            field=models.PositiveSmallIntegerField(choices=[('Poniżej 5 tys. km', 'Poniżej 5 tys. km'), ('do 10 tys. km', 'do 10 tys. km'), ('do 20 tys. km', 'do 20 tys. km'), ('powyżej 20 tys. km', 'powyżej 20 tys. km')]),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='policy_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='houseinsurance',
            name='house_type',
            field=models.CharField(choices=[('Dom', 'Dom'), ('Szeregowiec', 'Szeregowiec'), ('Mieszkanie', 'Mieszkanie')], max_length=100),
        ),
    ]
