# Generated by Django 5.0.2 on 2024-04-06 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_carinsurance_policy_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPolicyType',
            fields=[
                ('policy_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('policy_description', models.TextField()),
                ('type_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HousePolicyType',
            fields=[
                ('policy_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('policy_description', models.TextField()),
                ('type_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='carinsurance',
            name='policy_description',
        ),
        migrations.RemoveField(
            model_name='carinsurance',
            name='policy_name',
        ),
        migrations.RemoveField(
            model_name='houseinsurance',
            name='policy_description',
        ),
        migrations.RemoveField(
            model_name='houseinsurance',
            name='policy_name',
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='average_year_mileage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Poniżej 5 tys. km'), (2, 'do 10 tys. km'), (3, 'do 20 tys. km'), (4, 'powyżej 20 tys. km')]),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='policy_id',
            field=models.CharField(default='2024040622365241F4B', editable=False, max_length=19, primary_key=True, serialize=False, unique=True, verbose_name='20240406223652ADDF3'),
        ),
        migrations.AlterField(
            model_name='houseinsurance',
            name='policy_id',
            field=models.CharField(default='20240406223652C34D7', editable=False, max_length=19, primary_key=True, serialize=False, unique=True, verbose_name='202404062236525DD68'),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='policy_type',
            field=models.ForeignKey(default='Standard OC', on_delete=django.db.models.deletion.CASCADE, to='insurance_app.carpolicytype'),
        ),
        migrations.AddField(
            model_name='houseinsurance',
            name='policy_type',
            field=models.ForeignKey(default='Mieszkanie', on_delete=django.db.models.deletion.CASCADE, to='insurance_app.housepolicytype'),
        ),
    ]
