# Generated by Django 5.0.2 on 2024-04-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_carinsurance_customer_houseinsurance_customer'),
        ('insurance_app', '0005_carpolicytype_housepolicytype_policystatus_and_more'),
    ]

    operations = [
    ]
