# Generated by Django 5.0.2 on 2024-04-07 08:29

import django.db.models.deletion
import insurance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_carpolicytype_housepolicytype_policystatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinsurance',
            name='policy_type',
        ),
        migrations.AddField(
            model_name='houseinsurance',
            name='policy_type_ref',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.housepolicytype'),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='policy_id',
            field=models.CharField(default=insurance_app.models.generate_id, editable=False, max_length=19, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.carpolicytype'),
        ),
        migrations.AlterField(
            model_name='houseinsurance',
            name='policy_id',
            field=models.CharField(default=insurance_app.models.generate_id, editable=False, max_length=19, primary_key=True, serialize=False, unique=True),
        ),
    ]
