# Generated by Django 5.0.2 on 2024-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_alter_carinsurance_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurance',
            name='average_year_mileage',
            field=models.CharField(choices=[('Poniżej 5 tys. km', 'Poniżej 5 tys. km'), ('do 10 tys. km', 'do 10 tys. km'), ('do 20 tys. km', 'do 20 tys. km'), ('powyżej 20 tys. km', 'powyżej 20 tys. km')], max_length=100),
        ),
    ]
