# Generated by Django 5.0.2 on 2024-04-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0007_alter_carinsurance_average_year_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurance',
            name='average_year_mileage',
            field=models.PositiveIntegerField(choices=[(1, 'Poniżej 5 tys. km'), (2, 'do 10 tys. km'), (3, 'do 20 tys. km'), (4, 'powyżej 20 tys. km')], max_length=100),
        ),
    ]
