# Generated by Django 5.0.2 on 2024-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_carpolicytype_housepolicytype_policystatus_and_more'),
        ('insurance_app', '0007_alter_carinsurance_average_year_mileage'),
    ]

    operations = [
    ]
