# Generated by Django 5.0.2 on 2024-04-10 23:46

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_alter_carinsurance_average_year_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurance',
            name='production_year',
            field=models.PositiveIntegerField(default=2024, validators=[utils.validators.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='carinsurance',
            name='valid_to',
            field=models.DateField(validators=[utils.validators.validate_future_date]),
        ),
    ]
