# Generated by Django 5.0.2 on 2024-04-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_alter_carinsurance_production_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinsurance',
            name='car_model',
        ),
        migrations.AddField(
            model_name='carinsurance',
            name='car_mark_model',
            field=models.CharField(choices=[('Toyota Corolla:', 'Toyota Corolla:'), ('Skoda Octavia:', 'Skoda Octavia:'), ('Toyota Yaris:', 'Toyota Yaris:'), ('Toyota Yaris Cross:', 'Toyota Yaris Cross:'), ('Kia Sportage', 'Kia Sportage'), ('Toyota C-HR', 'Toyota C-HR'), ('Dacia Duster', 'Dacia Duster'), ('Toyota RAV4', 'Toyota RAV4'), ('Volkswagen T-Roc', 'Volkswagen T-Roc'), ('Kia Ceed', 'Kia Ceed'), ('BMW X3', 'BMW X3'), ('Kia Stonic', 'Kia Stonic'), ('Audi A4', 'Audi A4'), ('BMW Serii 3', 'BMW Serii 3'), ('Audi Q3', 'Audi Q3'), ('Audi Q5', 'Audi Q5'), ('Lexus NX', 'Lexus NX'), ('Suzuki Vitara', 'Suzuki Vitara'), ('Volkswagen Golf', 'Volkswagen Golf'), ('Nissan Qashqai', 'Nissan Qashqai'), ('Audi A3', 'Audi A3'), ('Renault Clio', 'Renault Clio'), ('Volkswagen Passat', 'Volkswagen Passat'), ('Dacia Sandero', 'Dacia Sandero')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
