# Generated by Django 5.0.2 on 2024-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_carpolicyfactors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='age_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='avg_year_mileage_1',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='avg_year_mileage_2',
            field=models.FloatField(default=0.07),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='avg_year_mileage_3',
            field=models.FloatField(default=0.09),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='avg_year_mileage_4',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='mileage_factor_1',
            field=models.FloatField(default=0.002),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='mileage_factor_2',
            field=models.FloatField(default=0.0033),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='mileage_factor_3',
            field=models.FloatField(default=0.0044),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='owners_factor_1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='owners_factor_2',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='owners_factor_3',
            field=models.FloatField(default=1.8),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='owners_factor_4',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='rented_factor_1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='carpolicyfactors',
            name='rented_factor_2',
            field=models.FloatField(default=3),
        ),
    ]
