# Generated by Django 5.0.2 on 2024-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_alter_carpolicyfactors_age_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpolicyfactors',
            name='base',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
        ),
    ]
