# Generated by Django 5.0.2 on 2024-04-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0015_housepolicyfactors'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepolicyfactors',
            name='base',
            field=models.FloatField(default=600),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_area_factor_1',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_area_factor_2',
            field=models.FloatField(default=1.1),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_area_factor_3',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_owners_factor_1',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_owners_factor_2',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_owners_factor_3',
            field=models.FloatField(default=1.8),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_owners_factor_4',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_value_factor_1',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_value_factor_2',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_value_factor_3',
            field=models.FloatField(default=1.8),
        ),
        migrations.AddField(
            model_name='housepolicyfactors',
            name='house_value_factor_4',
            field=models.FloatField(default=2),
        ),
    ]
