# Generated by Django 5.0.2 on 2024-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0016_housepolicyfactors_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinsurance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='houseinsurance',
            name='house_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='houseinsurance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
