# Generated by Django 5.0.2 on 2024-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0017_alter_carinsurance_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepolicyfactors',
            name='house_area_factor_1',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='housepolicyfactors',
            name='house_area_factor_2',
            field=models.FloatField(default=1.8),
        ),
        migrations.AlterField(
            model_name='housepolicyfactors',
            name='house_area_factor_3',
            field=models.FloatField(default=2),
        ),
    ]
